# Generated by Django 2.1.1 on 2018-09-08 13:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Athletes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isFeePayed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='People',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('athlethe', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='CrossBoxManager.Athletes')),
            ],
        ),
        migrations.CreateModel(
            name='SportClub',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('club_name', models.CharField(max_length=64, unique=True)),
                ('address', models.CharField(max_length=128)),
                ('nip', models.CharField(max_length=64)),
                ('bank_account', models.CharField(max_length=64)),
                ('founder', models.CharField(max_length=128)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('date_posted', models.DateTimeField()),
                ('typeOfmessage', models.CharField(choices=[('InterStaff', 'InterStaff'), ('InterAthlete', 'InterAthlete'), ('StaffAthlete', 'StaffAthlete')], max_length=128)),
                ('from_who', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='from_who', to='CrossBoxManager.People')),
                ('sport_club', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='CrossBoxManager.SportClub')),
                ('to_who', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='to_who', to='CrossBoxManager.People')),
            ],
        ),
        migrations.CreateModel(
            name='TreningEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trening_program', models.TextField()),
                ('date', models.DateTimeField()),
                ('members', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='CrossBoxManager.People')),
            ],
        ),
        migrations.CreateModel(
            name='TreningsHarmo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trening_name', models.CharField(max_length=64)),
                ('leading_trainer', models.CharField(max_length=63)),
                ('week_day', models.CharField(choices=[('Mon', 'Monday'), ('Tue', 'Tuesday'), ('Wed', 'Wednesday'), ('Thu', 'Thursday'), ('Fri', 'Friday'), ('Sat', 'Saturday'), ('Sun', 'Sunday')], max_length=128)),
                ('hour', models.TimeField(choices=[(8, 8), (9, 9), (16, 16), (17, 17), (18, 18), (19, 19), (20, 20), (21, 21)])),
                ('members', models.ManyToManyField(through='CrossBoxManager.TreningEvent', to='CrossBoxManager.People')),
                ('sport_club', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='CrossBoxManager.SportClub')),
            ],
        ),
        migrations.CreateModel(
            name='Workers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_manager', models.BooleanField(default=False)),
                ('is_accountant', models.BooleanField(default=False)),
                ('is_trener', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='treningevent',
            name='trening_harmo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='CrossBoxManager.TreningsHarmo'),
        ),
        migrations.AddField(
            model_name='people',
            name='sport_club',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='CrossBoxManager.SportClub'),
        ),
        migrations.AddField(
            model_name='people',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='people',
            name='worker',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='CrossBoxManager.Workers'),
        ),
    ]
