# Generated by Django 2.1.1 on 2019-02-12 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CrossBoxManager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='typeOfmessage',
            field=models.CharField(choices=[('', 'Select type of message'), ('InterStaff', 'InterStaff'), ('InterToAthlete', 'InterToAthlete'), ('StaffToAthlete', 'StaffToAthlete')], max_length=128),
        ),
        migrations.AlterField(
            model_name='treningsharmo',
            name='hour',
            field=models.TimeField(choices=[('', 'Select training hour'), (8, 8), (9, 9), (16, 16), (17, 17), (18, 18), (19, 19), (20, 20), (21, 21)]),
        ),
        migrations.AlterField(
            model_name='treningsharmo',
            name='leading_trainer',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='treningsharmo',
            name='week_day',
            field=models.CharField(choices=[('', 'Select training day'), ('Mon', 'Monday'), ('Tue', 'Tuesday'), ('Wed', 'Wednesday'), ('Thu', 'Thursday'), ('Fri', 'Friday'), ('Sat', 'Saturday'), ('Sun', 'Sunday')], max_length=128),
        ),
    ]
